server :
  port : 5000

spring:
  h2:
    console:
      enabled: true

  devtools:
    livereload:
      enabled: true

  thymeleaf:
    cache: false
    check-template-location: true
    prefix: file:src/main/resources/templates/
    suffix: .html

  datasource :
    driver-class-name : org.h2.Driver
    url : jdbc:h2:mem:test
    username : sa
    password :

  jpa :
    show_sql: true
    hibernate :
      ddl-auto : create